version: "3.9"

services:
  postgres-db:
    image: postgres:13-alpine
    volumes:
      - app-db-data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

  panel_admin:
    build:
      context: ./web
      dockerfile: panel_admin.dockerfile
    depends_on:
      - postgres-db
    env_file:
      - .env
    ports:
      - 5500:5500

volumes:
  app-db-data: null
